version: "3.7"

services:

  facemask-detection:
    build: ./src
    container_name: facemask-detection
    restart: always
    environment:
      - APP_NAME=facemask-detection
      - POST_TYPE=FILE
      - SAVE_PATH=./images/upload.png
    expose:
      - 8000
    command: uvicorn endpoints:app --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app



